### ISSUE TITLE
Input Coordinates should be able to handle the same coordinates as Coordinate Conversion

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbol-editor-addin-wpf#209] opened 2018-01-30 17:16 UTC
Currently the Regular expressions that are a part of Coordinate Conversion are not in Military Symbol Editor.

**Comment by csmoore** [comment] 2018-01-30 17:29
This addin is calling the Coordinate Conversion [library/code to do the parse](https://github.com/Esri/military-symbol-editor-addin-wpf/blob/dev/source/ProSymbolEditor/Utilities/ProSymbolUtilities.cs#L111) . 

Can you be a little more specific about the bug and some example scenarios that aren't working.

I'm not saying there isn't a problem, I just don't fully understand the current vs. intended behavior.

**Comment by topowright** [comment] 2018-02-02 17:51
We need to get the excel table from @elinz

**Comment by dfoll** [comment] 2018-03-01 22:24
-107° 25.4990' +28° 29.6578' and 107.424983W 28.494297N both worked for me on the Enter Coordinates tab, will need some specific examples of what is not working

**Comment by dfoll** [comment] 2018-06-14 22:48
closing. I cannot repro. It worked at our last released version as well

**Closed by dfoll** 2018-06-14 22:48 UTC
Labels: A-bug, E-invalid, G-QC Verify (Manual)
