### ISSUE TITLE
First time adding a favorite symbol to map draws unknown symbol

### ISSUE THREAD

**Issue by ACueva** [Esri/military-symbol-editor-addin-wpf#241] opened 2018-06-14 22:26 UTC
**Latest status from build 7 6/18/2018:**
User can still add Unknown symbols to the map after deleting an item from the Favorites list. See [last comment](https://github.com/Esri/military-symbol-editor-addin-wpf/issues/241#issuecomment-398174455).

Environment:
ArcGIS Pro 2.2 Daily
MilSymbol Editor Build 4 (6/14/2018)

Steps to Reproduce:

1. Start ArcGIS Pro
2. Create a new Map Project
3. Launch Military Symbol Editor
4. Go to Favorites Tab
5. Click Import
6. Import SampleFavorites.json.txt file attached to this issue (remove .txt extension and keep just .json)
7. Click on Favorite
8. Click on Pro Map if not visibile
9. Click on Add to Map Button
10. Add-In Disabled Form should prompt you to add the Military Overlay Schema
11. After Military Overlay Schema is added you should be able to add symbol to the map
12.  Note, if you try to add the symbol without clicking on any other symbol first, it will draw an unknown symbol.

![2018-06-14_15-14-28](https://user-images.githubusercontent.com/3093940/41441055-d659adb0-6fe5-11e8-89b0-21d11f748ab4.jpg)

13. If you click on any other symbol from the Military Symbol Editor Pane, and then click back to your original symbol, it will draw fine.
![2018-06-14_15-15-18](https://user-images.githubusercontent.com/3093940/41441077-f5fd0900-6fe5-11e8-9474-5dfda56dc189.jpg)

[SampleFavorites.json.txt](https://github.com/Esri/military-symbol-editor-addin-wpf/files/1907964/SampleFavorites.json.txt)

Other variations: 
I can also reproduce this behavior by immediately after importing a Favorites JSON file, not selecting any symbol, and clicking Add to Map.  Any symbol drawn will be of type "unknown".

If you click "Delete" and delete a symbol from your favorites list, you can still click "Add to Map", it will then allow you to add an unknown symbol on your map.

**Comment by topowright** [comment] 2018-06-14 22:52
This can be fixed by not enabling the add to map until something is selected in the find or favorites category.

**Comment by lfunkhouser** [comment] 2018-06-15 00:32
Adding to the current Sprint in hopes that it is an easy fix.

**Comment by dfoll** [comment] 2018-06-15 01:27
Very closely related to #243 and also indirectly related to #241

**Comment by csmoore** [comment] 2018-06-15 17:34
Hopefully addressed in PR #244 

I did try to address issue that when 

1. User starts with new Pro project
2. User selects favorite
3. Clicks Add to Map
4. Schema gets added
5. Click on Map
6. The previously selected favorite is not the symbol added to the map (unknown symbol or affiliation)

But I didn't explore all of the import favorites scenarios - so there may still be some issues there when combined with a new schema-less project.

**Comment by kgonzago** [comment] 2018-06-18 13:56
testing with our latest build.

**Comment by kgonzago** [comment] 2018-06-18 19:38
My testing did not include the changes @csmoore made in [PR 244](https://github.com/Esri/military-symbol-editor-addin-wpf/pull/244) since it was never reviewed and merged. Doing that now.

**Comment by kgonzago** [comment] 2018-06-18 19:40
Changes were reviewed and merged. Kicked off a new MSE add-in build.

**Comment by kgonzago** [comment] 2018-06-18 19:52
After [PR 244](https://github.com/Esri/military-symbol-editor-addin-wpf/pull/244), I verified `Unknown` symbols cannot be added to a map after importing the JSON file. However, I am still able to add `Unknown` symbols after deleting an item from the Favorties list:

![image](https://user-images.githubusercontent.com/6391826/41558658-81a8b0ea-730f-11e8-8f67-d640c5b64626.png)

**Comment by topowright** [comment] 2018-06-19 16:21
The issue at hand is that when you do not have a item selected in the favorites tab the button reverts back to the last item in the search window. 
The expected behavior is the button is not available when their is not an item in the favorites tab.

**Comment by dfoll** [comment] 2018-06-22 22:44
With MSE build 11 on 2.2 final this is fixed

**Closed by dfoll** 2018-06-22 22:44 UTC
Labels: A-bug, ESTIMATE, G-Development, G-QC Verify (Manual)
