### ISSUE TITLE
Favorites tab holds on to preview of symbols from previous session, but the frame/affiliation is lost

### ISSUE THREAD

**Issue by dfoll** [Esri/military-symbol-editor-addin-wpf#243] opened 2018-06-15 01:20 UTC
1. Open MSE and search for "cavalry hostile"
2. After being prompted to add the schema to your project, add a hostile cavalry symbol to your map
3. After adding to your map, use the Add Favorites button to add it to your favorites tab
4. Observe that it is added to your favorites tab
5. Close Pro (either saving edit or not, I haven't seen that it matters)
6. Open Pro with a new project, and go directly to the favorites tab
7. Observer that the cavalry symbol from the previous project is still there and it is reading all tags and appears ok.
8. Click the symbol then click add to map
9. You are prompted to add the schema (this is expected, as this is a new project that you have not added the schema yet issue. #242 is a tangentially related but completely separate issue)
10. Add the schema, click on the symbol in your favorites tab, then click the Add to Map button
11. Click on the map. 
12. A cavalry with an unknown frame is added to the map
![image](https://user-images.githubusercontent.com/5322669/41445584-69199dae-6fff-11e8-80d0-155a8657f1a3.png)

_**further exploration**_
1. Click on the Search tab
2. Search for "mechanized friend"
3. Add that to favorites
4. That adds to the map
5. Click back on the hostile cavalry symbol
6. The hostile cavalry from your favorites now adds correctly
![image](https://user-images.githubusercontent.com/5322669/41445595-77026a4a-6fff-11e8-9971-6ed9f1275a48.png)

I do not know enough about the code to explain, but it has something to do with Search being used before it will work correctly, as @ACueva noticed something nearly identical, with different steps to get there, in #241

**Comment by dfoll** [comment] 2018-06-15 01:28
#241 and #242 are separated but both revolve around the same subject matter

**Comment by csmoore** [comment] 2018-06-15 18:04
@dfoll - I believe you are correct that this is the same issue reported in #241 (minus the import favorites steps) so hopefully this is fixed with https://github.com/Esri/military-symbol-editor-addin-wpf/issues/241#issuecomment-397691475 and PR #244 

Removing dev tag to mark for retest

**Comment by kgonzago** [comment] 2018-06-18 19:35
Tested with build 6 of MSE add-in. I am still able to reproduce the issue the the steps listed in the [main comment](https://github.com/Esri/military-symbol-editor-addin-wpf/issues/243#issue-332615725).

![image](https://user-images.githubusercontent.com/6391826/41557927-3ad707b8-730d-11e8-89d6-cdbb1242c9c0.png)

**Comment by kgonzago** [comment] 2018-06-18 19:41
My testing did not include the changes @csmoore made in [PR 244](https://github.com/Esri/military-symbol-editor-addin-wpf/pull/244) since it was never reviewed and merged.

**Comment by kgonzago** [comment] 2018-06-18 19:59
After [PR 244](https://github.com/Esri/military-symbol-editor-addin-wpf/pull/244) was reviewed and merged, using the steps detailed in the [main comment](https://github.com/Esri/military-symbol-editor-addin-wpf/issues/243#issue-332615725), I verified this issue is fixed:
![image](https://user-images.githubusercontent.com/6391826/41558950-92d374da-7310-11e8-9f49-e541d4db03ff.png)

**Closed** 2018-06-19 20:19 UTC
Labels: A-bug, E-verified, S-Military Symbol Editor, S-Military Tools, V -  Pro 2.1
