### ISSUE TITLE
Static Code Analyzer : Empty Catch Block

### ISSUE THREAD

**Issue by jmccausland** [Esri/military-symbol-editor-addin-wpf#199] opened 2017-10-05 19:35 UTC
- remove try/catch or comment if needed but does nothing

**Comment by csmoore** [comment] 2018-04-06 14:49
This has been addressed - except in ProSymbolUtilities.GetCoordinateType where this behavior (trying a coordinate and catching the exception if it can't be parsed ) is by design

**Comment by csmoore** [comment] 2018-04-09 15:14
Addressed in PR #220 

Moving to done and will get reviewed/QA/QC with SCA Issue #197

**Closed** 2018-04-13 00:11 UTC
Labels: T-SCA
