### ISSUE TITLE
Tags are not displayed for modified symbols on the Favorites tab

### ISSUE THREAD

**Issue by elinz** [Esri/military-symbol-editor-addin-wpf#113] opened 2016-11-10 23:35 UTC
Unmodified symbol displays tags on the Favorites tab:
![image](https://cloud.githubusercontent.com/assets/4635490/20198723/16fd7928-a75b-11e6-8964-d76f5214ab89.png)

Modified symbol does not display tags on the Favorites tab:
![image](https://cloud.githubusercontent.com/assets/4635490/20198759/3af5c5f6-a75b-11e6-8420-caeda80be1f5.png)

I would expect that the same symbol with a modified would still have all the tags as the original unmodified symbol.

To replicate the issue:

1. Open Pro 1.2
2. Create new project from Map template
3. Perform a search in the Search tab for "Infantry"
4. Select "Movement and Maneuver : Infantry : Friend"
5. When prompted that you don't have the schema, click yes to create schema in project file geodatabase. At this point the Search tab will have a preview of the symbol and will list the tags of the symbol at the bottom of the preview area.
6. Click "Add to Map", and click somewhere on the map to place the new feature.
7. Click "Add Favorite". New entry is added to list in Favorites tab.
8. Click on the newly added entry in Favorites tab. The tags and the symbol are showned in the preview area of the Favorites tab.
9. On the map, select the newly added feature. Click on the Symbol tab. Change Echelon to "Platoon/Detachment" (The symbol in the preview area is updated). Click "Save Edits" (the feature on the map is updated).
10. Click "Add Favorite". Examine Favorites tab (a new entry is added to the Favorites list.
11. Click on the new entry in the Favorites list. Issue: the tags for the modified feature, i.e. "Movement and Maneuver : Infantry : Friend", platoon are not displayed.

**Comment by csmoore** [comment] 2016-11-10 23:43
This is a duplicate of https://github.com/Esri/military-symbol-editor-addin-wpf/issues/103 but your description is better so I'll close that one and leave this one open

**Comment by csmoore** [comment] 2017-01-09 18:24
This should be fixed for newly saved symbols (favorites saved before this fix will still have blank tags, so should be deleted before testing).

**Comment by csmoore** [comment] 2017-01-11 19:17
@elinz - can you verify in the next build (1.2 or 1.4) - thanks

**Comment by joebayles** [comment] 2017-01-11 22:13
I can verify that this works in 1.4.

![image](https://cloud.githubusercontent.com/assets/5016557/21868553/28867ab8-d808-11e6-9c1e-27bd65a199f3.png)

**Closed** 2017-01-11 22:17 UTC
Labels: 3 - Verify, B - Bug, priority - normal, V - Pro 1.2
