### ISSUE TITLE
Create Feature Templates from Pro Symbol Editor Add-in (Using Pro SDK)

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-symbol-editor-addin-wpf#83] opened 2016-07-26 15:47 UTC
Currently, we are trying to replicate the Create Feature Template workflow directly in our Symbol Editor Add-In, but can't find a way to do it using the Pro SDK. 

**Core workflow in Pro:**
- Open Manage Templates Pane:
- Select Create Template from Feature:
  ![image](https://cloud.githubusercontent.com/assets/13024357/17144071/69746950-530a-11e6-9398-e8085f8c7643.png)
- Configure your Feature Template:
  ![image](https://cloud.githubusercontent.com/assets/13024357/17144110/8b56d332-530a-11e6-9f59-09193ce91a1e.png)

Is there a way we could create a Feature Template from a selected feature in our Symbol Editor Add-In? This would require a "Create Template from Feature" option in the Pro SDK. 

This is what our Add-In looks like now with a feature selected, we would want to have another button that would add the selected feature as a feature template:
![image](https://cloud.githubusercontent.com/assets/13024357/17144994/8ba3f218-530d-11e6-9cc2-feffa2a07cd7.png)

**Comment by jmccausland** [comment] 2016-07-26 16:03
@Dbarnes1 check out this really old project, I created a feature template from an xml file for Pro 1.1

[https://github.com/Esri/military-planner-application-csharp/tree/master/source/arcgis-pro-import-feature-templates](url)

**Comment by csmoore** [comment] 2016-07-26 16:22
@jmccausland - thanks - that looks like what we were looking for:  https://github.com/Esri/military-planner-application-csharp/blob/master/source/arcgis-pro-import-feature-templates/arcgis-pro-import-feature-templates/ImportFeaturesTemplateButton.cs#L175

**Comment by nfeuerstein** [comment] 2016-12-15 00:19
Is this issue still valid? @Dbarnes1 @csmoore

**Comment by csmoore** [comment] 2016-12-15 13:51
@Dbarnes1 would just need to confirm if he still wants this specific enhancement request (to add a button to create a feature template).

Adding to the main symbol UI/tab might unnecessarily clutter this tab for something that may not be a common workflow - so maybe we could just add it to the favorites tab instead.

**Comment by BobBooth** [comment] 2016-12-15 14:52
@csmoore & @Dbarnes1 - it could be a setting (on the Settings dialog) that they could toggle off or on, to either create feature templates also, or not create feature templates, whenever you create a favorite.
Alternately, if could be a button on the Favorites tab to create template from selected Favorite (would be nice to be able to select multiple Favs).

**Comment by Dbarnes1** [comment] 2016-12-15 15:19
@csmoore @nfeuerstein @BobBooth this is still a valid enhancement, but I think we should push this off to v2 given our timeline, etc. Changing tag from **question** to **enhancement**

**Comment by nfeuerstein** [comment] 2016-12-15 16:47
I assigned the "version-after next" milestone, so this should not be a priority for this release.

**Comment by Dbarnes1** [comment] 2017-02-23 00:01
@nfeuerstein we should take a look at this for our next military tools release, as it would be a key enhancement that would allow us to dynamically flow from military symbol editor to feature templates and back.

**Comment by csmoore** [comment] 2017-04-21 17:38
Prototyping/Implementing this was straightforward (Note: this button is just for a quick demo, we can do the workflow/UI however you decide) :

![image](https://cloud.githubusercontent.com/assets/3090809/25288956/af98f810-2695-11e7-8e26-dd993a9e9063.png)

Source/Branch: https://github.com/Esri/military-symbol-editor-addin-wpf/compare/csm/favorite-to-template

However, there seems to be an issue/bug in that adding the template does not refresh the Pro Create or Manage Feature Template Panes:

1. Add the template from the SDK/Mil Symbol Editor - template does not get added to the template panes
![image](https://cloud.githubusercontent.com/assets/3090809/25289017/ef35eadc-2695-11e7-9d33-273ca3de889c.png)

2. Do something to force the Pane to be updated - like restart Pro or move the layer in the TOC and the template appears:
![image](https://cloud.githubusercontent.com/assets/3090809/25289127/69bfe244-2696-11e7-89f1-8c1442504cde.png)

Since this presumably worked back when @jmccausland [implemented this for the mil planner demo app](https://github.com/Esri/military-planner-application-csharp/tree/master/source/arcgis-pro-import-feature-templates/arcgis-pro-import-feature-templates) we might have to (1) presume this is a bug at 1.4 (2) try on 2.0 to see if fixed, and/or (3) report the bug if not. We are just following [the SDK example/snippet](https://github.com/Esri/arcgis-pro-sdk/wiki/ProConcepts-Editing#creating-and-modifying-feature-templates) so not sure how we could be doing this wrong. I tried several workarounds but could not get the template panes to refresh/update.

**Comment by csmoore** [comment] 2017-04-25 16:14
Just a quick update to the last comment above, I confirmed that adding a feature template through the Pro SDK now works as expected at Pro 2.0 (tested on Pro 2.0.8614 Beta): the template is added and updated on the Pro UIs as expected - this appears to have just been a bug at 1.4.

**Comment by csmoore** [comment] 2017-05-04 21:10
One more, more update on this - I also tested this at 1.4.1 and this works there also so was just a bug at 1.4 - if we are targeting 1.4.1+ then we can do this issue/enhancement.  Sorry for not testing on this version earlier - fyi @nfeuerstein @lfunkhouser

**Comment by nfeuerstein** [comment] 2017-05-16 19:08
Will be addressed at 2.0

**Comment by dfoll** [comment] 2017-06-14 22:19
verified, moving to in progress for documenting

**Comment by dfoll** [comment] 2017-06-14 23:02
documented

**Comment by dfoll** [comment] 2017-06-16 18:05
opened this back up and put to in progress and assigned for @NatalieCampos  to review

**Comment by NatalieCampos** [comment] 2017-06-21 17:36
documentation reviewed

**Closed by NatalieCampos** 2017-06-21 17:36 UTC
Labels: 4 - Done, B - Affects Documentation, B - Enhancement, effort-medium
