### ISSUE TITLE
MSE should be able to to draw symbols the same way they are drawn using the symbology pane in ArcGIS Pro

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbol-editor-addin-wpf#182] opened 2017-06-21 22:51 UTC
Currently when you search for a symbol in MSE and try to use an SIDC code it is challenging because the add in searches based on a tag column in the sql lite database and does not use the SIDC code the same way that ArcGIS Pro uses the stylex file to draw. 

An example would be to use the following code:  

If I use ArcGIS Pro to draw the SFGPUCI---AF--- , which is an example symbol from a customer I get the correct symbol rendered on the map: 

![image](https://user-images.githubusercontent.com/5488313/27410228-11a30ff2-569b-11e7-9a6b-e36427e3afbd.png)

If I try and use this same SIDC code in MSE it cannot find the symbol. This is because we are looking at the tags in the database and not the keys. The keys are used by ArcGIS Pro to draw this symbol. 

![image](https://user-images.githubusercontent.com/5488313/27410314-a1f8fb98-569b-11e7-9688-e539f213e33a.png)

As a user I would not understand that in order to make this symbol appear it would need to be given to MSE in the following format

**Comment by lfunkhouser** [comment] 2018-08-14 20:27
Closing. Duplicate of #178.  Added clarifying information to #178 regarding searching on keys to support SIDC search.

**Closed by lfunkhouser** 2018-08-14 20:27 UTC
Labels: E-duplicate
